services:
  uta:
    # Test:
    # psql -XAt postgres://anonymous@localhost/uta -c 'select count(*) from uta_20241220.transcript'
    # 329090
    image: biocommons/uta:uta_20241220
    environment:
      - POSTGRES_PASSWORD=some-password-that-you-make-up
    volumes:
      - uta_vol:/var/lib/postgresql/data
      - type: bind
        source: ./uta_20241220.pgd.gz
        target: /tmp/uta_20241220.pgd.gz
        read_only: true
        bind:
          create_host_path: false
      - ./uta-setup.sql:/docker-entrypoint-initdb.d/uta-setup.sql
    ports:
      - 127.0.0.1:5432:5432

volumes:
  uta_vol:
    external: true
